---
- name: ensure user exists
  ansible.builtin.user:
    name: "{{ fetch_ssl_script_owner }}"
    groups:
      - "{{ fetch_ssl_script_group }}"
    append: yes
  register: _fetch_ssl_script_owner_info

- name: generate script
  ansible.builtin.include_tasks: "{{ fetch_ssl_certificate_source }}.yaml"

- name: run script
  ansible.builtin.command:
    cmd: "{{ fetch_ssl_script_dir }}/{{ fetch_ssl_script_name }}"
  become: true
  become_user: "{{ fetch_ssl_script_owner }}"
  when: fetch_ssl_run_now
